In [379]:
import numpy as np


def prod_non_zero_diag(x):
    """Compute product of nonzero elements from matrix diagonal.

    input:
    x -- 2-d numpy array
    output:
    product -- integer number


    Vectorized implementation.
    """
    x = x.diagonal()
    x = x[np.nonzero(x)]
    return x.prod()
    pass


def are_multisets_equal(x, y):
    """Return True if both vectors create equal multisets.

    input:
    x, y -- 1-d numpy arrays
    output:
    True if multisets are equal, False otherwise -- boolean

    Vectorized implementation.
    """
    x.sort()
    y.sort()
    return np.all(x == y)
    pass


def max_after_zero(x):
    """Find max element after zero in array.

    input:
    x -- 1-d numpy array
    output:
    maximum element after zero -- integer number

    Vectorized implementation.
    """
    z = np.where(x == 0)[0] + 1
    x = np.append(x, x.min())
    return x[z].max()
    pass

def convert_image(img, coefs):
    """Sum up image channels with weights from coefs array

    input:
    img -- 3-d numpy array (H x W x num_channels)
    coefs -- 1-d numpy array (length num_channels)
    output:
    img -- 2-d numpy array

    Vectorized implementation.
    """
    img = np.multiply(img[:, :], coefs)
    #print(img)
    return np.sum(img, axis = 2)
    pass


def run_length_encoding(x):
    """Make run-length encoding.

    input:
    x -- 1-d numpy array
    output:
    elements, counters -- integer iterables

    Vectorized implementation.
    """
    n = len(x)
    starts = np.r_[0, np.flatnonzero(~(x[1:] == x[:-1])) + 1]
    lengths = np.diff(np.r_[starts, n])
    values = x[starts]
    return values, lengths
    pass

#    return np.linalg.norm(a - b)

def substract_vect(a, b):
    return a - b

def pairwise_distance(x, y):
    """Return pairwise object distance.

    input:
    x, y -- 2d numpy arrays
    output:
    distance array -- 2d numpy array

    Vectorized implementation.
    """
    n = x.shape[0]
    m = y.shape[0]
    k = x.shape[1]
    a = np.repeat(x, m, axis=0).reshape(n, m, k) 
    b = np.repeat(y[:][np.newaxis][:], n, axis=0)
    z = a - b 
    return np.apply_along_axis(np.linalg.norm, 2, z)  

In [52]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

In [53]:
prod_non_zero_diag(X)

3

In [54]:
X = np.array([1, 2, 2, 4])
Y = np.array([4, 2, 1, 2])

In [55]:
are_multisets_equal(X, Y)

True

In [56]:
are_multisets_equal(np.array([1, 2, 3, 3]), np.array([1, 2, 2, 3]))

False

In [295]:
X = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

In [296]:
max_after_zero(X)

5

In [297]:
max_after_zero(np.array([0, 0, -5]))

0

In [142]:
X = np.array([2, 2, 2, 3, 3, 3, 5])

In [150]:
run_length_encoding(X)

(array([2, 3, 5]), array([3, 3, 1]))

In [381]:
pairwise_distance(np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]))

array([[ 5.65685425,  8.48528137],
       [ 2.82842712,  5.65685425]])

In [382]:
pairwise_distance(np.array([[1, 9], [2, 5]]), np.array([[3, 8], [9, 0]]))

array([[  2.23606798,  12.04159458],
       [  3.16227766,   8.60232527]])

In [383]:
pairwise_distance(np.array([[1, 9], [2, 5], [7, 7]]), np.array([[3, 8], [9, 0], [8, 2]]))

array([[  2.23606798,  12.04159458,   9.89949494],
       [  3.16227766,   8.60232527,   6.70820393],
       [  4.12310563,   7.28010989,   5.09901951]])

In [236]:
import scipy.spatial

In [237]:
scipy.spatial.distance.cdist([[1, 2], [3, 4]], [[5, 6], [7, 8]])

array([[ 5.65685425,  8.48528137],
       [ 2.82842712,  5.65685425]])

In [384]:
%timeit pairwise_distance(np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]))

433 µs ± 33.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [239]:
%timeit scipy.spatial.distance.cdist([[1, 2], [3, 4]], [[5, 6], [7, 8]])

96 µs ± 746 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [281]:
import imageio
img = imageio.imread('img.png')
buf = convert_image(np.array(img), np.array([0.299, 0.587, 0.114]))

36.3 ms ± 4.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [277]:
imageio.imwrite('result.png', np.array(buf))